'''
HTML documentation for L{pysenorge}.

Generated by I{epydoc}.

Download and install I{epydoc} and run the following command::
    epydoc.py --html ~/pysenorge -o ~/pysenorge/doc/html --docformat epytext -v

@author: kmu
@since: 15. aug. 2010
'''